native-image --no-server \
	--class-path build/libs/*.jar \
	-H:ReflectionConfigurationFiles=build/reflect.json \
	-H:EnableURLProtocols=http \
	-H:IncludeResources="logback.xml|application.yml" \
	-H:Name=micronaut \
	-H:Class=com.mageddo.micronaut.Application \
	-H:+ReportUnsupportedElementsAtRuntime \
	-H:+AllowVMInspection \
	--allow-incomplete-classpath \
	--rerun-class-initialization-at-runtime='sun.security.jca.JCAUtil$CachedSecureRandomHolder,javax.net.ssl.SSLContext' \
	--delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder,io.netty.handler.codec.http.websocketx.WebSocket00FrameEncoder,io.netty.handler.ssl.util.ThreadLocalInsecureRandom,com.sun.jndi.dns.DnsClient
