CREATE TABLE IF NOT EXISTS FRUITS (
	NAM_FRUIT VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FRUITS_TRACE (
	DAT_OCCURENCE VARCHAR (255) NOT NULL
);

INSERT INTO FRUITS VALUES ('GRAPE'), ('STRAWBERRY'), ('APPLE'), ('ORANGE'), ('BLUEBERRY');
