version: '3'
services:
  postgres:
    image: postgres:11
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5433:5432
    volumes:
      - ./src/main/resources/db/migrations:/docker-entrypoint-initdb.d
