FROM adoptopenjdk/openjdk8:x86_64-ubuntu-jdk8u362-b09 AS BULDER
COPY ./ /app
WORKDIR /app
RUN ./gradlew build shadowjar
ENTRYPOINT [ \
  "java", "-jar", "/app/build/libs/graalvm-jna-all.jar" \
]
#adoptopenjdk/openjdk8:x86_64-ubuntu-jre8u362-b09 java -jar /app.jar

#FROM debian:9-slim
#COPY --from=BULDER /app/build/native/nativeCompile/graalvm-jna /bin/graalvm-jna
#ENTRYPOINT /bin/graalvm-jna
