---
micronaut:
  application:
    name: micronaut
  router:
    static-resources:
      default:
        mapping: /static/**
        paths:
          - classpath:static
---
datasources:
  default:
    jdbcUrl: jdbc:postgresql://0.0.0.0:5433/db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    connectionTestQuery: SELECT 1
    initializationFailTimeout: -1
    minimumIdle: 1
    maximumPoolSize: 10
---
micronaut:
  views:
    folder: templates
